# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
# permalink: /:categories/:year/:month/:day/:title 
root: /
permalink: blog/:categories/:year/:month/:day/:title 
markdown: kramdown
paginate: 5

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: wavelet


title: Xiaobo WU's blog